version: '3.1'
services:
  db:
    image: postgres:latest # TODO: Lock image version
    container_name: peasy-fit-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: peasy-fit-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db